spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://182.92.166.86:3306/corpus
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      max-lifetime: 30000
      connection-test-query: SELECT 1
  thymeleaf:
    cache: false
  jpa:
    properties:
      hibernate:
        hibernate:
          generate_statistics: true
        jdbc:
          batch_size: 1000
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
    hibernate:
      use-new-id-generator-mappings: false


logging:
  file:
    path: /var/log