spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://182.92.166.86:3306/corpus
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
#     池中维护的最小空闲连接数
      minimum-idle: 5
#     池中最大连接数
      maximum-pool-size: 20
#     池中连接最长的生命周期
      max-lifetime: 180000
#     连接测试语句
      connection-test-query: SELECT 1
#     连接允许在池中闲置的最长时间
      idle-timeout: 60000
    type: com.zaxxer.hikari.HikariDataSource
  thymeleaf:
    cache: false
  jpa:
    properties:
      hibernate:
        hibernate:
          generate_statistics: true
        jdbc:
          batch_size: 1000
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
    hibernate:
      use-new-id-generator-mappings: false


logging:
  file:
    path: /var/log